name: yspot_project
description: A new Flutter project.

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  #Ui Dependencies

  flutter_screenutil:
  animated_text_kit:
  google_fonts:
  floating_bottom_navigation_bar: ^1.5.2
  syncfusion_flutter_datepicker: ^25.2.4
  intl: any

  #Language feature

  flutter_localization:

  #Otp page

  intl_phone_field:
  otp_autofill:
  otp_timer:
  flutter_otp_text_field:

  #other

  flutter_svg: ^2.0.10+1
  filter_list: ^1.0.2
  expandable: ^5.0.1
  staggered_grid_view_flutter: ^0.0.4
  data_filters: ^1.0.2
  url_launcher: any

  #Firebase Dependencies

  firebase_core: ^2.31.0
  firebase_auth:
  google_sign_in:
  firebase_storage: ^11.7.6
  cloud_firestore: ^4.17.4


  #Maps Dependencies

  google_maps_flutter: ^2.6.1
  google_polyline_points: ^0.0.3
  location: ^6.0.2
  maps_launcher: ^2.2.1
  geolocator:

  percent_indicator: ^4.2.3


  cupertino_icons: ^1.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true


  assets:
     - assets/
     - assets/logo assets/
     - assets/button assets/
     - assets/sample assets/
     - assets/icons/



  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
